# def generate_definition():
#     return {
#         "$schema": "https://powerbi.microsoft.com/product/schema#report",
#         "version": "1.0",
#         "type": "Report",
#         "settings": {
#             "defaultMode": "Edit"
#         }
#     }


# def generate_item_config(report_name):
#     return {
#         "name": report_name,
#         "description": "PBIR report generated by automation",
#         "type": "Report"
#     }


def generate_definition() -> dict:
    """
    Generate PBIR report definition with proper schema and settings
    """
    return {
        "$schema": "https://powerbi.microsoft.com/product/schema#report",
        "version": "1.0",
        "type": "Report",
        "settings": {
            "defaultMode": "Edit"
        },
        "pages": [],   # Pages will be added at runtime if needed
        "datasets": [] # Dataset will be linked at runtime
    }

def generate_item_config(report_name: str) -> dict:
    """
    Generate report item config for PBIR
    """
    return {
        "name": report_name,
        "description": "PBIR report generated by automation",
        "type": "Report"
    }
