def get_report_name(metadata: dict) -> str:
    """
    Safely extract report/workbook name from different metadata shapes
    """
    return (
        metadata.get("workbook")
        or metadata.get("workbookName")
        or metadata.get("name")
        or metadata.get("title")
        or "AutoGeneratedReport"
    )


def extract_worksheets(metadata: dict) -> list:
    """
    Normalize worksheets from different Tableau metadata shapes.
    Always returns a list of worksheet dicts.
    """

    # Case 1: {"worksheets": [ ... ]}
    if "worksheets" in metadata and isinstance(metadata["worksheets"], list):
        return metadata["worksheets"]

    # Case 2: {"worksheets": {"worksheet": [ ... ]}}
    if "worksheets" in metadata and isinstance(metadata["worksheets"], dict):
        return metadata["worksheets"].get("worksheet", [])

    # Case 3: {"sheets": [ ... ]}
    if "sheets" in metadata:
        return metadata["sheets"]

    # Case 4: {"workbook": {"worksheets": [ ... ]}}
    if "workbook" in metadata and isinstance(metadata["workbook"], dict):
        return metadata["workbook"].get("worksheets", [])

    raise ValueError("❌ No worksheets found in metadata")


def extract_columns(worksheet: dict) -> list:
    """
    Extract column list from a worksheet safely
    """
    if "columns" in worksheet and isinstance(worksheet["columns"], list):
        return worksheet["columns"]

    if "fields" in worksheet:
        return worksheet["fields"]

    return []
